sLogDailyReports/Models/Shift.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace sLogDailyReports.Models
{
    public class Shift
    {
        public int Id { get; set; }
        [DisplayName("Nazwa")]
        public string ShiftName { get; set; }
        [DisplayName("Początek zmiany")]
        public int ShiftStart { get; set; }
        [DisplayName("Koniec zmiany")]
        public int ShiftEnd { get; set; }
    }
}

sLogDailyReports/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sLogDailyReports.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

sLogDailyReports/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sLogDailyReports.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        public IndexModel(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult OnGet()
        {
            if (_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToPage("Report/Index");
            }
            return Page();
        }
    }
}

sLogDailyReports/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sLogDailyReports.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

sLogDailyReports/Pages/Shifts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using sLogDailyReports.Models;
using sLogDailyReports.Repositories.Shifts;

namespace sLogDailyReports.Pages
{
    [Authorize]
    public class ShiftsModel : PageModel
    {
        [BindProperty]
        public List<Shift> Shifts { get; set; }

        [BindProperty]
        public Shift NewShift { get; set; }

        public List<SelectListItem> Hours { get; set; }

        public bool EditMode = false;

        private readonly IShiftsRepository _shiftsRepository;

        public ShiftsModel(IShiftsRepository shiftsRepository)
        {
            _shiftsRepository = shiftsRepository;
        }

        public void OnGet()
        {
            Hours = new List<SelectListItem>();
            for (int i = 0; i < 24; i++)
            {
                Hours.Add(new SelectListItem(i + ":00", i.ToString()));
            }
            Shifts = _shiftsRepository.GetAll().ToList();
        }

        public IActionResult OnPostDelete(int id)
        {
            _shiftsRepository.Delete(id);

            return RedirectToPage("Shifts");
        }

        public IActionResult OnPostSaveShift(int id, List<Shift> shifts)
        {
            _shiftsRepository.Update(shifts.Single(s => s.Id == id));
            return RedirectToPage("Shifts");
        }

        public IActionResult OnPostSaveNewShift()
        {
            _shiftsRepository.AddNew(NewShift);
            return RedirectToPage("Shifts");
        }
    }
}

sLogDailyReports/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


    <div class="text-center">
        <h1 class="display-4">Witaj</h1>
        <p>Aby korzystać z aplikacji <a href="/Account/Login">Zaloguj się</a>.</p>
    </div>

sLogDailyReports/Pages/Shifts.cshtml
@page
@model sLogDailyReports.Pages.ShiftsModel
@{
    ViewData["Title"] = "Shifts";
}

<h1>Zmiany</h1>

<form method="post">
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Shifts[0].ShiftName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shifts[0].ShiftStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shifts[0].ShiftEnd)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @for (var i = 0; i < Model.Shifts.Count(); i++)
        {
            <tr id="shiftDisplay_@Model.Shifts[i].Id">
                <td>
                    @Html.DisplayFor(modelItem => Model.Shifts[i].ShiftName)
                </td>
                <td>
                    @Model.Shifts[i].ShiftStart:00
                </td>
                <td>
                    @Model.Shifts[i].ShiftEnd:00
                </td>
                <td>
                    <span class="editButtons">
                        <button class="btn btn-outline-info editButton" type="button" onclick="EditShift(@Model.Shifts[i].Id)">Edytuj</button> |
                        <button class="btn btn-danger" type="submit" asp-page-handler="delete" asp-route-id="@Model.Shifts[i].Id">Usuń</button>
                    </span>
                </td>
            </tr>
            <tr id="shiftEdit_@Model.Shifts[i].Id" hidden>
                <td>
                    <input asp-for="@Model.Shifts[i].Id" type="hidden"/><input asp-for="@Model.Shifts[i].ShiftName" class="form-control"/>
                </td>
                <td>
                    <select asp-for="@Model.Shifts[i].ShiftStart" asp-items="@(new SelectList(Model.Hours, "Value", "Text"))" class="form-control"></select>
                </td>
                <td>
                    <select asp-for="@Model.Shifts[i].ShiftEnd" asp-items="@(new SelectList(Model.Hours, "Value", "Text"))" class="form-control"></select>
                </td>
                <td>
                    <button class="btn btn-outline-primary" type="submit" asp-page-handler="saveShift" asp-route-id="@Model.Shifts[i].Id">Zapisz</button> |
                    <button class="btn btn-secondary" type="button" onclick="UndoEditShift(@Model.Shifts[i].Id)">Cofnij</button>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <button type="button" class="btn btn-primary" bs-toggle-modal="addShift">Nowa zmiana</button>
</form>

<modal title="Dodaj nową zmianę"id="addShift">
    <modal-body>
        <form method="post">
            <div class="form-row">
                <label asp-for="NewShift.ShiftName" class="col-form-label"></label> <input asp-for="NewShift.ShiftName" class="form-control" />
            </div>
            <div class="form-row">
                <label asp-for="NewShift.ShiftStart" class="col-form-label"></label> <select asp-for="NewShift.ShiftStart" asp-items="@(new SelectList(Model.Hours, "Value", "Text"))" class="form-control" ></select>
            </div>
            <div class="form-row">
                <label asp-for="NewShift.ShiftEnd" class="col-form-label"></label> <select asp-for="NewShift.ShiftEnd" asp-items="@(new SelectList(Model.Hours, "Value", "Text"))" class="form-control"></select>
            </div>
            <div class="border-top"></div>
            <br/><button class="btn btn-outline-primary" type="submit" asp-page-handler="saveNewShift">Zapisz</button>
            <div asp-validation-summary="All"></div>
        </form>
    </modal-body>
</modal>
<script>
    var editMode = false;
    function EditShift(id) {
        document.getElementById('shiftDisplay_' + id).setAttribute('hidden', '');
        document.getElementById('shiftEdit_' + id).removeAttribute('hidden');

        $('.editButtons').hide();
        $('#newShift').hide();
    }

    function UndoEditShift(id) {
        document.getElementById('shiftDisplay_' + id).removeAttribute('hidden');
        document.getElementById('shiftEdit_' + id).setAttribute('hidden', '');

        $('.editButtons').show();
        $('#newShift').show();
    }
</script>