sLogDailyReports/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace sLogDailyReports.Models
{
    public class Group
    {
        public int Id { get; set; }
        [Display(Name="Nazwa")]
        public string Name { get; set; }
        [Display(Name="Stanowiska")]
        public IList<Station> Stations { get; set; }
        
    }
}

sLogDailyReports/Pages/Groups/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using sLogDailyReports.Models;
using sLogDailyReports.Repositories.Groups;
using sLogDailyReports.Repositories.Stations;

namespace sLogDailyReports.Pages.Groups
{
    [Authorize]
    public class EditModel : PageModel
    {
        public Group Group { get; set; }
        public IList<Station> AvailableStations { get; set; }

        private readonly IGroupsRepository _groupsRepository;
        private readonly IStationsRepository _stationsRepository;

        public EditModel(IGroupsRepository groupsRepository, IStationsRepository stationsRepository)
        {
            _groupsRepository = groupsRepository;
            _stationsRepository = stationsRepository;
        }

        public void OnGet(int id)
        {
            Group = _groupsRepository.GetById(id);
            AvailableStations = _stationsRepository.GetAllUnassigned().ToList();
        }

        public IActionResult OnPostSaveGroup()
        {
            var stationsIds = Request.Form["StationId"].ToArray();
            var groupId = int.Parse(Request.Path.ToString().Split('/').Last());

            _groupsRepository.AddStations(groupId, Array.ConvertAll(stationsIds, id => int.Parse(id)));

            return RedirectToPage("/Groups/Edit", new { id = groupId });
        }

        public IActionResult OnPostRemoveStations()
        {
            var groupId = int.Parse(Request.Path.ToString().Split('/').Last());
            var stationsIds = Request.Form["StationId"].ToArray();

            _groupsRepository.RemoveStations(groupId, Array.ConvertAll(stationsIds, id => int.Parse(id)));

            return RedirectToPage("/Groups/Edit", new { id = groupId });
        }
    }
}

sLogDailyReports/Pages/Groups/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using sLogDailyReports.Models;
using sLogDailyReports.Repositories.Groups;

namespace sLogDailyReports.Pages.Groups
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public List<Group> Groups { get; set; }

        [BindProperty]
        public Group NewGroup { get; set; }

        private readonly IGroupsRepository _groupsRepository;

        public IndexModel(IGroupsRepository groupsRepository)
        {
            _groupsRepository = groupsRepository;
        }

        public void OnGet()
        {
            Groups = _groupsRepository.GetAll().ToList();
            NewGroup = new Group();
        }

        public IActionResult OnPostSaveGroup()
        {
            _groupsRepository.Create(NewGroup);
            return RedirectToPage("/Groups/Edit", new { id = NewGroup.Id });
        }

        public IActionResult OnPostDeleteGroup()
        {
            var r = Request.Form;
            _groupsRepository.Delete(int.Parse(Request.Form["Id"]));

            return new JsonResult(new { success = true });
        }
    }
}

sLogDailyReports/Pages/Groups/Edit.cshtml
@page "{id:int}"
@model sLogDailyReports.Pages.Groups.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Stanowiska w grupie "@Model.Group.Name"</h1>

<ul>
    @for (var i = 0; i < Model.Group.Stations.Count(); i++)
    {
        <li>@Model.Group.Stations[i].Description (@Model.Group.Stations[i].Name)</li>
    }
</ul>

<button type="button" class="btn btn-primary" bs-toggle-modal="addStations">Dodaj stanowiska</button>
<button type="button" class="btn btn-danger" bs-toggle-modal="removeStations">Usuń stanowiska</button>

<modal title="Dodaj stanowiska do grupy" id="addStations">
    <modal-body>
        <form method="post">
            @for (var i = 0; i < Model.AvailableStations.Count(); i++)
            {
                <input type="checkbox" name="StationId" value="@Model.AvailableStations[i].Id" />
                <span>@Model.AvailableStations[i].Description (@Model.AvailableStations[i].Name)</span><br />
            }
            <br /><button class="btn btn-outline-primary" type="submit" asp-page-handler="saveGroup">Zapisz</button>

            <div asp-validation-summary="All"></div>
        </form>
    </modal-body>
</modal>

<modal title="Usuń stanowiska z grupy" id="removeStations">
    <modal-body>
        <form method="post">
            @for (var i = 0; i < Model.Group.Stations.Count(); i++)
            {
                <input type="checkbox" name="StationId" value="@Model.Group.Stations[i].Id" />
                <span>@Model.Group.Stations[i].Description (@Model.Group.Stations[i].Name)</span><br />
            }
            <br /><button class="btn btn-outline-danger" type="submit" asp-page-handler="removeStations">Zapisz</button>

            <div asp-validation-summary="All"></div>
        </form>
    </modal-body>
</modal>

sLogDailyReports/Pages/Groups/Index.cshtml
@page
@model sLogDailyReports.Pages.Groups.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>Grupy</h1>

<table class="table">
    <thead>
    <tr>
        <th><label asp-for="@Model.Groups[0].Name"></label></th>
    </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < Model.Groups.Count(); i++)
    {
        <tr id="group_@Model.Groups[i].Id">
            <td>
                @Html.DisplayFor(m => @Model.Groups[i].Name)
            </td>
            <td>
                <a href="Groups/Edit/@Model.Groups[i].Id" class="btn btn-outline-primary">Edytuj</a> | <button type="button" class="btn btn-danger" onclick="deleteGroup(@Model.Groups[i].Id)">Usuń</button>
            </td>
        </tr>
    }
    </tbody>
</table>
<div class="modal" tabindex="-1" role="dialog" id="newGroupModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <form method="post">
                <div class="modal-header">
                    <h5 class="modal-title">Podaj nazwę grupy</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input asp-for="@Model.NewGroup.Name" class="form-control"/>
                </div>
                <div class="modal-footer">
                    <button type="submit" asp-page-handler="saveGroup" class="btn btn-primary">Zapisz</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                </div>
            </form>
        </div>
    </div>
</div>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newGroupModal" >Dodaj grupę</button>

@section scripts {
    <script>
        function deleteGroup(id) {
            $.ajax({
                url: '/Groups?handler=deleteGroup',
                method: "POST",
                contentType: "application/x-www-form-urlencoded",
                data: { "Id": id },
                headers:
                {
                    "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val()
                },
                success: function (result) {
                    if (result.success === true)
                        deleteGroupTableRow(id);
                    else alert("Nie udało się usunąć");
                },
                error: function (error) {
                    alert("Nie udało się usunąć" + error);
                }
            });
        }

        function deleteGroupTableRow(id) {
            $('#group_' + id).remove();
        }
    </script>
}